SKILL_LABELS = [
    # Core Technical Skills
    "Machine Learning",
    "Deep Learning", 
    "Data Analysis",
    "Data Science",
    "Programming",
    "Software Engineering",
    "Database Management",
    "Cybersecurity",
    "Cloud Computing",
    "Web Development",
    "Mobile Development",
    "Blockchain",
    "Artificial Intelligence",
    "Computer Vision",
    "Natural Language Processing",
    
    # System & Infrastructure
    "Operating Systems",
    "Computer Networks",
    "DevOps",
    "System Administration",
    "Microservices",
    "Containerization",
    "Distributed Systems",
    "High Performance Computing",
    
    # Data & Analytics
    "Data Visualization",
    "Statistics",
    "Mathematics",
    "Big Data",
    "Data Mining",
    "Business Intelligence",
    "Data Engineering",
    "Data Warehousing",
    
    # Programming Languages & Frameworks
    "Python",
    "JavaScript",
    "Java",
    "C++",
    "React",
    "Node.js",
    "Django",
    "Flask",
    "Spring",
    "Angular",
    "Vue.js",
    
    # Specialized Domains
    "Game Development",
    "Embedded Systems",
    "Robotics",
    "IoT Development",
    "AR/VR Development",
    "Quantum Computing",
    "Bioinformatics",
    "Fintech",
    "HealthTech",
    "EdTech",
    
    # Soft Skills & Management
    "Communication",
    "Leadership",
    "Project Management",
    "Problem Solving",
    "Critical Thinking",
    "Teamwork",
    "Agile Development",
    "Scrum",
    "Product Management",
    "Technical Writing",
    "Presentation Skills",
    "Mentoring",
    
    # Research & Innovation
    "Research Methods",
    "Innovation",
    "Patent Analysis",
    "Technology Trends",
    "Academic Writing",
    "Experimental Design",
    "Scientific Computing",
    
    # Business & Domain Knowledge
    "Business Analysis",
    "User Experience Design",
    "UI/UX Design",
    "Digital Marketing",
    "E-commerce",
    "Supply Chain",
    "Finance",
    "Healthcare",
    "Education",
    "Government",
    "Non-profit"
]
